### ISSUE TITLE
Дълбоко копие, а не плитко!

### ISSUE THREAD

**Issue by dabidesh** [softuni-quiz/softuni-quiz.github.io#1]
https://github.com/softuni-quiz/softuni-quiz.github.io/blob/3732fab5ead5fdb3c2cb82abab5b5aeba6f8649d/quizes/02.json#L167
Не трябва ли да е **дълбоко** копие (клониране)?

**Comment by dabidesh** [comment]
Сега прочетох, че и плиткото копие е клониране ... грешно бях разбрал термина!

**Comment by viktorpts** [comment]
Тъкмо започнах с отговора :) Ще го оставя все пак, за други читатели:

Дълбоко копие е когато всяко свойство на всички елементи от масива се копират в нови елементи. `slice()` копира елементите по стойност, съответно ако те са референтни, копира референцията, а не индивидуалните свойства.
